version: "3.9"

services:
  db:
    build:
      context: ./db
      args:
        - environment=test
    env_file:
      - db/.env.testing
    volumes:
    - "test_dbdata:/var/lib/postgresql/data"

  backend:
    build:
      context: ./backend
      args:
        - environment=test

  tg_sender:
    build:
      context: ./backend
      args:
        - environment=test

  frontend:
    build:
      context: ./frontend
      args:
        - environment=test
    env_file:
      - frontend/.env.testing

volumes:
  test_dbdata:
